// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: janction/videoUpscaler/v1/query.proto

package videoUpscaler

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryGetGameRequest is the request type for the Query/GetGame RPC
// method.
type QueryGetVideoUpscalerTaskRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetVideoUpscalerTaskRequest) Reset()         { *m = QueryGetVideoUpscalerTaskRequest{} }
func (m *QueryGetVideoUpscalerTaskRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetVideoUpscalerTaskRequest) ProtoMessage()    {}
func (*QueryGetVideoUpscalerTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7aa663478f7b9c9b, []int{0}
}
func (m *QueryGetVideoUpscalerTaskRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVideoUpscalerTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVideoUpscalerTaskRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVideoUpscalerTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVideoUpscalerTaskRequest.Merge(m, src)
}
func (m *QueryGetVideoUpscalerTaskRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVideoUpscalerTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVideoUpscalerTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVideoUpscalerTaskRequest proto.InternalMessageInfo

func (m *QueryGetVideoUpscalerTaskRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

// QueryGetGameResponse is the response type for the Query/GetGame RPC
// method.
type QueryGetVideoUpscalerTaskResponse struct {
	// Game defines the game at the requested index.
	VideoUpscalerTask *VideoUpscalerTask `protobuf:"bytes,1,opt,name=video_upscaler_task,json=videoUpscalerTask,proto3" json:"video_upscaler_task,omitempty"`
}

func (m *QueryGetVideoUpscalerTaskResponse) Reset()         { *m = QueryGetVideoUpscalerTaskResponse{} }
func (m *QueryGetVideoUpscalerTaskResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetVideoUpscalerTaskResponse) ProtoMessage()    {}
func (*QueryGetVideoUpscalerTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7aa663478f7b9c9b, []int{1}
}
func (m *QueryGetVideoUpscalerTaskResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVideoUpscalerTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVideoUpscalerTaskResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVideoUpscalerTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVideoUpscalerTaskResponse.Merge(m, src)
}
func (m *QueryGetVideoUpscalerTaskResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVideoUpscalerTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVideoUpscalerTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVideoUpscalerTaskResponse proto.InternalMessageInfo

func (m *QueryGetVideoUpscalerTaskResponse) GetVideoUpscalerTask() *VideoUpscalerTask {
	if m != nil {
		return m.VideoUpscalerTask
	}
	return nil
}

// QueryGetGameRequest is the request type for the Query/GetGame RPC
// method.
type QueryGetVideoUpscalerLogsRequest struct {
	ThreadId string `protobuf:"bytes,1,opt,name=threadId,proto3" json:"threadId,omitempty"`
}

func (m *QueryGetVideoUpscalerLogsRequest) Reset()         { *m = QueryGetVideoUpscalerLogsRequest{} }
func (m *QueryGetVideoUpscalerLogsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetVideoUpscalerLogsRequest) ProtoMessage()    {}
func (*QueryGetVideoUpscalerLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7aa663478f7b9c9b, []int{2}
}
func (m *QueryGetVideoUpscalerLogsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVideoUpscalerLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVideoUpscalerLogsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVideoUpscalerLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVideoUpscalerLogsRequest.Merge(m, src)
}
func (m *QueryGetVideoUpscalerLogsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVideoUpscalerLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVideoUpscalerLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVideoUpscalerLogsRequest proto.InternalMessageInfo

func (m *QueryGetVideoUpscalerLogsRequest) GetThreadId() string {
	if m != nil {
		return m.ThreadId
	}
	return ""
}

// QueryGetGameResponse is the response type for the Query/GetGame RPC
// method.
type QueryGetVideoUpscalerLogsResponse struct {
	// Game defines the game at the requested index.
	VideoUpscalerLogs *VideoUpscalerLogs `protobuf:"bytes,1,opt,name=video_upscaler_logs,json=videoUpscalerLogs,proto3" json:"video_upscaler_logs,omitempty"`
}

func (m *QueryGetVideoUpscalerLogsResponse) Reset()         { *m = QueryGetVideoUpscalerLogsResponse{} }
func (m *QueryGetVideoUpscalerLogsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetVideoUpscalerLogsResponse) ProtoMessage()    {}
func (*QueryGetVideoUpscalerLogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7aa663478f7b9c9b, []int{3}
}
func (m *QueryGetVideoUpscalerLogsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVideoUpscalerLogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVideoUpscalerLogsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVideoUpscalerLogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVideoUpscalerLogsResponse.Merge(m, src)
}
func (m *QueryGetVideoUpscalerLogsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVideoUpscalerLogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVideoUpscalerLogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVideoUpscalerLogsResponse proto.InternalMessageInfo

func (m *QueryGetVideoUpscalerLogsResponse) GetVideoUpscalerLogs() *VideoUpscalerLogs {
	if m != nil {
		return m.VideoUpscalerLogs
	}
	return nil
}

type QueryGetPendingVideoUpscalerTaskRequest struct {
}

func (m *QueryGetPendingVideoUpscalerTaskRequest) Reset() {
	*m = QueryGetPendingVideoUpscalerTaskRequest{}
}
func (m *QueryGetPendingVideoUpscalerTaskRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPendingVideoUpscalerTaskRequest) ProtoMessage()    {}
func (*QueryGetPendingVideoUpscalerTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7aa663478f7b9c9b, []int{4}
}
func (m *QueryGetPendingVideoUpscalerTaskRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPendingVideoUpscalerTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPendingVideoUpscalerTaskRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPendingVideoUpscalerTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPendingVideoUpscalerTaskRequest.Merge(m, src)
}
func (m *QueryGetPendingVideoUpscalerTaskRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPendingVideoUpscalerTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPendingVideoUpscalerTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPendingVideoUpscalerTaskRequest proto.InternalMessageInfo

type QueryGetPendingVideoUpscalerTaskResponse struct {
	VideoUpscalerTasks []*VideoUpscalerTask `protobuf:"bytes,1,rep,name=video_upscaler_tasks,json=videoUpscalerTasks,proto3" json:"video_upscaler_tasks,omitempty"`
}

func (m *QueryGetPendingVideoUpscalerTaskResponse) Reset() {
	*m = QueryGetPendingVideoUpscalerTaskResponse{}
}
func (m *QueryGetPendingVideoUpscalerTaskResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPendingVideoUpscalerTaskResponse) ProtoMessage()    {}
func (*QueryGetPendingVideoUpscalerTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7aa663478f7b9c9b, []int{5}
}
func (m *QueryGetPendingVideoUpscalerTaskResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPendingVideoUpscalerTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPendingVideoUpscalerTaskResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPendingVideoUpscalerTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPendingVideoUpscalerTaskResponse.Merge(m, src)
}
func (m *QueryGetPendingVideoUpscalerTaskResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPendingVideoUpscalerTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPendingVideoUpscalerTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPendingVideoUpscalerTaskResponse proto.InternalMessageInfo

func (m *QueryGetPendingVideoUpscalerTaskResponse) GetVideoUpscalerTasks() []*VideoUpscalerTask {
	if m != nil {
		return m.VideoUpscalerTasks
	}
	return nil
}

type QueryGetWorkerRequest struct {
	Worker string `protobuf:"bytes,1,opt,name=worker,proto3" json:"worker,omitempty"`
}

func (m *QueryGetWorkerRequest) Reset()         { *m = QueryGetWorkerRequest{} }
func (m *QueryGetWorkerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetWorkerRequest) ProtoMessage()    {}
func (*QueryGetWorkerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7aa663478f7b9c9b, []int{6}
}
func (m *QueryGetWorkerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetWorkerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetWorkerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetWorkerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetWorkerRequest.Merge(m, src)
}
func (m *QueryGetWorkerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetWorkerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetWorkerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetWorkerRequest proto.InternalMessageInfo

func (m *QueryGetWorkerRequest) GetWorker() string {
	if m != nil {
		return m.Worker
	}
	return ""
}

type QueryGetWorkerResponse struct {
	Worker *Worker `protobuf:"bytes,1,opt,name=worker,proto3" json:"worker,omitempty"`
}

func (m *QueryGetWorkerResponse) Reset()         { *m = QueryGetWorkerResponse{} }
func (m *QueryGetWorkerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetWorkerResponse) ProtoMessage()    {}
func (*QueryGetWorkerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7aa663478f7b9c9b, []int{7}
}
func (m *QueryGetWorkerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetWorkerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetWorkerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetWorkerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetWorkerResponse.Merge(m, src)
}
func (m *QueryGetWorkerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetWorkerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetWorkerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetWorkerResponse proto.InternalMessageInfo

func (m *QueryGetWorkerResponse) GetWorker() *Worker {
	if m != nil {
		return m.Worker
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetVideoUpscalerTaskRequest)(nil), "janction.videoUpscaler.v1.QueryGetVideoUpscalerTaskRequest")
	proto.RegisterType((*QueryGetVideoUpscalerTaskResponse)(nil), "janction.videoUpscaler.v1.QueryGetVideoUpscalerTaskResponse")
	proto.RegisterType((*QueryGetVideoUpscalerLogsRequest)(nil), "janction.videoUpscaler.v1.QueryGetVideoUpscalerLogsRequest")
	proto.RegisterType((*QueryGetVideoUpscalerLogsResponse)(nil), "janction.videoUpscaler.v1.QueryGetVideoUpscalerLogsResponse")
	proto.RegisterType((*QueryGetPendingVideoUpscalerTaskRequest)(nil), "janction.videoUpscaler.v1.QueryGetPendingVideoUpscalerTaskRequest")
	proto.RegisterType((*QueryGetPendingVideoUpscalerTaskResponse)(nil), "janction.videoUpscaler.v1.QueryGetPendingVideoUpscalerTaskResponse")
	proto.RegisterType((*QueryGetWorkerRequest)(nil), "janction.videoUpscaler.v1.QueryGetWorkerRequest")
	proto.RegisterType((*QueryGetWorkerResponse)(nil), "janction.videoUpscaler.v1.QueryGetWorkerResponse")
}

func init() {
	proto.RegisterFile("janction/videoUpscaler/v1/query.proto", fileDescriptor_7aa663478f7b9c9b)
}

var fileDescriptor_7aa663478f7b9c9b = []byte{
	// 538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xcd, 0x4a, 0xcc, 0x4b,
	0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2f, 0xcb, 0x4c, 0x49, 0xcd, 0x0f, 0x2d, 0x28, 0x4e, 0x4e, 0xcc,
	0x49, 0x2d, 0xd2, 0x2f, 0x33, 0xd4, 0x2f, 0x2c, 0x4d, 0x2d, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x92, 0x84, 0x29, 0xd3, 0x43, 0x51, 0xa6, 0x57, 0x66, 0x28, 0x85, 0xc7, 0x84, 0x92,
	0xca, 0x82, 0xd4, 0x62, 0x88, 0x09, 0x52, 0x32, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x89,
	0x05, 0x99, 0xfa, 0x89, 0x79, 0x79, 0xf9, 0x25, 0x89, 0x20, 0x3d, 0x30, 0x59, 0xe9, 0xe4, 0xfc,
	0xe2, 0xdc, 0xfc, 0x62, 0x88, 0x9d, 0x68, 0x96, 0x4b, 0x89, 0xa4, 0xe7, 0xa7, 0xe7, 0x83, 0x99,
	0xfa, 0x20, 0x16, 0x44, 0x54, 0xc9, 0x82, 0x4b, 0x21, 0x10, 0xa4, 0xc8, 0x3d, 0xb5, 0x24, 0x0c,
	0xd9, 0xe2, 0x90, 0xc4, 0xe2, 0xec, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x11, 0x2e,
	0xd6, 0xcc, 0xbc, 0x94, 0xd4, 0x0a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0x47, 0xa9,
	0x91, 0x91, 0x4b, 0x11, 0x8f, 0xd6, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0xa1, 0x18, 0x2e, 0x61,
	0xb0, 0x87, 0xe2, 0x4b, 0xa1, 0xb2, 0xf1, 0x25, 0x89, 0xc5, 0xd9, 0x60, 0x93, 0xb8, 0x8d, 0x74,
	0xf4, 0x70, 0x06, 0x88, 0x1e, 0xa6, 0x91, 0x82, 0x65, 0xe8, 0x42, 0x4a, 0x76, 0x38, 0x5c, 0xef,
	0x93, 0x9f, 0x5e, 0x0c, 0x73, 0xbd, 0x14, 0x17, 0x47, 0x49, 0x46, 0x51, 0x6a, 0x62, 0x8a, 0x67,
	0x0a, 0xd4, 0x03, 0x70, 0x3e, 0x6e, 0x3f, 0x40, 0x0c, 0xc0, 0xe9, 0x87, 0x9c, 0xfc, 0xf4, 0x62,
	0x52, 0xfd, 0x00, 0x36, 0x12, 0xd5, 0x0f, 0x20, 0x21, 0x25, 0x4d, 0x2e, 0x75, 0x98, 0x13, 0x02,
	0x52, 0xf3, 0x52, 0x32, 0xf3, 0xd2, 0x71, 0x45, 0x84, 0x52, 0x17, 0x23, 0x97, 0x06, 0x61, 0xb5,
	0x50, 0x57, 0xc7, 0x71, 0x89, 0x60, 0x09, 0x79, 0x90, 0xb3, 0x99, 0x49, 0x0e, 0x7a, 0x21, 0x8c,
	0xa0, 0x2f, 0x56, 0xd2, 0xe7, 0x12, 0x85, 0xb9, 0x25, 0x3c, 0xbf, 0x28, 0x3b, 0xb5, 0x08, 0x16,
	0xe0, 0x62, 0x5c, 0x6c, 0xe5, 0x60, 0x01, 0x68, 0x70, 0x43, 0x79, 0x4a, 0xc1, 0x5c, 0x62, 0xe8,
	0x1a, 0xa0, 0x4e, 0xb5, 0x44, 0xd1, 0xc1, 0x6d, 0xa4, 0x88, 0xc7, 0x71, 0x50, 0xad, 0x50, 0x0d,
	0x46, 0x4f, 0x59, 0xb9, 0x58, 0xc1, 0xa6, 0x0a, 0x1d, 0x62, 0xe4, 0x12, 0xc1, 0x96, 0x14, 0x85,
	0xac, 0xf1, 0x98, 0x46, 0x28, 0xed, 0x4b, 0xd9, 0x90, 0xa7, 0x19, 0xe2, 0x31, 0x25, 0xfd, 0x8e,
	0xe7, 0x1b, 0xb4, 0x18, 0x9b, 0x2e, 0x3f, 0x99, 0xcc, 0xa4, 0x22, 0xa4, 0xa4, 0x8f, 0x3b, 0x8f,
	0x57, 0x83, 0xf3, 0x54, 0xad, 0xd0, 0x51, 0x2c, 0x9e, 0x00, 0xa5, 0x12, 0xd2, 0x3d, 0x81, 0x94,
	0x05, 0x48, 0xf7, 0x04, 0x72, 0xf2, 0x57, 0x32, 0x42, 0x78, 0x42, 0x5d, 0x48, 0x15, 0x9f, 0x27,
	0x60, 0xf9, 0xaa, 0x56, 0x68, 0x11, 0x23, 0x17, 0x27, 0x3c, 0x9e, 0x85, 0x0c, 0x88, 0xb0, 0x1f,
	0x25, 0x0d, 0x49, 0x19, 0x92, 0xa0, 0x03, 0xea, 0x4c, 0x03, 0x84, 0x33, 0x55, 0x85, 0x94, 0xf1,
	0x39, 0x13, 0x92, 0x74, 0x6a, 0x85, 0x56, 0x32, 0x72, 0xc9, 0xe0, 0xc9, 0x49, 0xc5, 0x42, 0x4e,
	0x44, 0xb8, 0x82, 0x40, 0x9e, 0x95, 0x72, 0xa6, 0xc8, 0x0c, 0xa8, 0xdf, 0x18, 0x9c, 0xac, 0x4f,
	0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18,
	0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21, 0x4a, 0x31, 0x3d, 0xb3, 0x24, 0xa3, 0x34,
	0x49, 0x2f, 0x39, 0x3f, 0x17, 0x87, 0xa7, 0x93, 0xd8, 0xc0, 0x65, 0xbd, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x97, 0x87, 0x92, 0xf2, 0xa7, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// GetVideoUpscalerTask returns the task based on the taskId
	GetVideoUpscalerTask(ctx context.Context, in *QueryGetVideoUpscalerTaskRequest, opts ...grpc.CallOption) (*QueryGetVideoUpscalerTaskResponse, error)
	GetVideoUpscalerLogs(ctx context.Context, in *QueryGetVideoUpscalerLogsRequest, opts ...grpc.CallOption) (*QueryGetVideoUpscalerLogsResponse, error)
	GetWorker(ctx context.Context, in *QueryGetWorkerRequest, opts ...grpc.CallOption) (*QueryGetWorkerResponse, error)
	GetPendingVideoUpscalerTasks(ctx context.Context, in *QueryGetPendingVideoUpscalerTaskRequest, opts ...grpc.CallOption) (*QueryGetPendingVideoUpscalerTaskResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetVideoUpscalerTask(ctx context.Context, in *QueryGetVideoUpscalerTaskRequest, opts ...grpc.CallOption) (*QueryGetVideoUpscalerTaskResponse, error) {
	out := new(QueryGetVideoUpscalerTaskResponse)
	err := c.cc.Invoke(ctx, "/janction.videoUpscaler.v1.Query/GetVideoUpscalerTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetVideoUpscalerLogs(ctx context.Context, in *QueryGetVideoUpscalerLogsRequest, opts ...grpc.CallOption) (*QueryGetVideoUpscalerLogsResponse, error) {
	out := new(QueryGetVideoUpscalerLogsResponse)
	err := c.cc.Invoke(ctx, "/janction.videoUpscaler.v1.Query/GetVideoUpscalerLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetWorker(ctx context.Context, in *QueryGetWorkerRequest, opts ...grpc.CallOption) (*QueryGetWorkerResponse, error) {
	out := new(QueryGetWorkerResponse)
	err := c.cc.Invoke(ctx, "/janction.videoUpscaler.v1.Query/GetWorker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetPendingVideoUpscalerTasks(ctx context.Context, in *QueryGetPendingVideoUpscalerTaskRequest, opts ...grpc.CallOption) (*QueryGetPendingVideoUpscalerTaskResponse, error) {
	out := new(QueryGetPendingVideoUpscalerTaskResponse)
	err := c.cc.Invoke(ctx, "/janction.videoUpscaler.v1.Query/GetPendingVideoUpscalerTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// GetVideoUpscalerTask returns the task based on the taskId
	GetVideoUpscalerTask(context.Context, *QueryGetVideoUpscalerTaskRequest) (*QueryGetVideoUpscalerTaskResponse, error)
	GetVideoUpscalerLogs(context.Context, *QueryGetVideoUpscalerLogsRequest) (*QueryGetVideoUpscalerLogsResponse, error)
	GetWorker(context.Context, *QueryGetWorkerRequest) (*QueryGetWorkerResponse, error)
	GetPendingVideoUpscalerTasks(context.Context, *QueryGetPendingVideoUpscalerTaskRequest) (*QueryGetPendingVideoUpscalerTaskResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetVideoUpscalerTask(ctx context.Context, req *QueryGetVideoUpscalerTaskRequest) (*QueryGetVideoUpscalerTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoUpscalerTask not implemented")
}
func (*UnimplementedQueryServer) GetVideoUpscalerLogs(ctx context.Context, req *QueryGetVideoUpscalerLogsRequest) (*QueryGetVideoUpscalerLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoUpscalerLogs not implemented")
}
func (*UnimplementedQueryServer) GetWorker(ctx context.Context, req *QueryGetWorkerRequest) (*QueryGetWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorker not implemented")
}
func (*UnimplementedQueryServer) GetPendingVideoUpscalerTasks(ctx context.Context, req *QueryGetPendingVideoUpscalerTaskRequest) (*QueryGetPendingVideoUpscalerTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPendingVideoUpscalerTasks not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetVideoUpscalerTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetVideoUpscalerTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetVideoUpscalerTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/janction.videoUpscaler.v1.Query/GetVideoUpscalerTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetVideoUpscalerTask(ctx, req.(*QueryGetVideoUpscalerTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetVideoUpscalerLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetVideoUpscalerLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetVideoUpscalerLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/janction.videoUpscaler.v1.Query/GetVideoUpscalerLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetVideoUpscalerLogs(ctx, req.(*QueryGetVideoUpscalerLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/janction.videoUpscaler.v1.Query/GetWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetWorker(ctx, req.(*QueryGetWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetPendingVideoUpscalerTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPendingVideoUpscalerTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetPendingVideoUpscalerTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/janction.videoUpscaler.v1.Query/GetPendingVideoUpscalerTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetPendingVideoUpscalerTasks(ctx, req.(*QueryGetPendingVideoUpscalerTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "janction.videoUpscaler.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVideoUpscalerTask",
			Handler:    _Query_GetVideoUpscalerTask_Handler,
		},
		{
			MethodName: "GetVideoUpscalerLogs",
			Handler:    _Query_GetVideoUpscalerLogs_Handler,
		},
		{
			MethodName: "GetWorker",
			Handler:    _Query_GetWorker_Handler,
		},
		{
			MethodName: "GetPendingVideoUpscalerTasks",
			Handler:    _Query_GetPendingVideoUpscalerTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "janction/videoUpscaler/v1/query.proto",
}

func (m *QueryGetVideoUpscalerTaskRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVideoUpscalerTaskRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVideoUpscalerTaskRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetVideoUpscalerTaskResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVideoUpscalerTaskResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVideoUpscalerTaskResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VideoUpscalerTask != nil {
		{
			size, err := m.VideoUpscalerTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetVideoUpscalerLogsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVideoUpscalerLogsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVideoUpscalerLogsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ThreadId) > 0 {
		i -= len(m.ThreadId)
		copy(dAtA[i:], m.ThreadId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ThreadId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetVideoUpscalerLogsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVideoUpscalerLogsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVideoUpscalerLogsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VideoUpscalerLogs != nil {
		{
			size, err := m.VideoUpscalerLogs.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPendingVideoUpscalerTaskRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPendingVideoUpscalerTaskRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPendingVideoUpscalerTaskRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetPendingVideoUpscalerTaskResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPendingVideoUpscalerTaskResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPendingVideoUpscalerTaskResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VideoUpscalerTasks) > 0 {
		for iNdEx := len(m.VideoUpscalerTasks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VideoUpscalerTasks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetWorkerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetWorkerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetWorkerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Worker) > 0 {
		i -= len(m.Worker)
		copy(dAtA[i:], m.Worker)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Worker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetWorkerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetWorkerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetWorkerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Worker != nil {
		{
			size, err := m.Worker.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetVideoUpscalerTaskRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetVideoUpscalerTaskResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VideoUpscalerTask != nil {
		l = m.VideoUpscalerTask.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetVideoUpscalerLogsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ThreadId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetVideoUpscalerLogsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VideoUpscalerLogs != nil {
		l = m.VideoUpscalerLogs.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPendingVideoUpscalerTaskRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetPendingVideoUpscalerTaskResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.VideoUpscalerTasks) > 0 {
		for _, e := range m.VideoUpscalerTasks {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryGetWorkerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Worker)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetWorkerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Worker != nil {
		l = m.Worker.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetVideoUpscalerTaskRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVideoUpscalerTaskRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVideoUpscalerTaskRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVideoUpscalerTaskResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVideoUpscalerTaskResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVideoUpscalerTaskResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VideoUpscalerTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.VideoUpscalerTask == nil {
				m.VideoUpscalerTask = &VideoUpscalerTask{}
			}
			if err := m.VideoUpscalerTask.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVideoUpscalerLogsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVideoUpscalerLogsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVideoUpscalerLogsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ThreadId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ThreadId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVideoUpscalerLogsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVideoUpscalerLogsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVideoUpscalerLogsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VideoUpscalerLogs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.VideoUpscalerLogs == nil {
				m.VideoUpscalerLogs = &VideoUpscalerLogs{}
			}
			if err := m.VideoUpscalerLogs.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPendingVideoUpscalerTaskRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPendingVideoUpscalerTaskRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPendingVideoUpscalerTaskRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPendingVideoUpscalerTaskResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPendingVideoUpscalerTaskResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPendingVideoUpscalerTaskResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VideoUpscalerTasks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VideoUpscalerTasks = append(m.VideoUpscalerTasks, &VideoUpscalerTask{})
			if err := m.VideoUpscalerTasks[len(m.VideoUpscalerTasks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetWorkerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetWorkerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetWorkerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Worker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Worker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetWorkerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetWorkerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetWorkerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Worker", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Worker == nil {
				m.Worker = &Worker{}
			}
			if err := m.Worker.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
