// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: janction/videoUpscaler/v1/query.proto

package videoUpscalerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_GetVideoUpscalerTask_FullMethodName         = "/janction.videoUpscaler.v1.Query/GetVideoUpscalerTask"
	Query_GetVideoUpscalerLogs_FullMethodName         = "/janction.videoUpscaler.v1.Query/GetVideoUpscalerLogs"
	Query_GetWorker_FullMethodName                    = "/janction.videoUpscaler.v1.Query/GetWorker"
	Query_GetPendingVideoUpscalerTasks_FullMethodName = "/janction.videoUpscaler.v1.Query/GetPendingVideoUpscalerTasks"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// GetVideoUpscalerTask returns the task based on the taskId
	GetVideoUpscalerTask(ctx context.Context, in *QueryGetVideoUpscalerTaskRequest, opts ...grpc.CallOption) (*QueryGetVideoUpscalerTaskResponse, error)
	GetVideoUpscalerLogs(ctx context.Context, in *QueryGetVideoUpscalerLogsRequest, opts ...grpc.CallOption) (*QueryGetVideoUpscalerLogsResponse, error)
	GetWorker(ctx context.Context, in *QueryGetWorkerRequest, opts ...grpc.CallOption) (*QueryGetWorkerResponse, error)
	GetPendingVideoUpscalerTasks(ctx context.Context, in *QueryGetPendingVideoUpscalerTaskRequest, opts ...grpc.CallOption) (*QueryGetPendingVideoUpscalerTaskResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetVideoUpscalerTask(ctx context.Context, in *QueryGetVideoUpscalerTaskRequest, opts ...grpc.CallOption) (*QueryGetVideoUpscalerTaskResponse, error) {
	out := new(QueryGetVideoUpscalerTaskResponse)
	err := c.cc.Invoke(ctx, Query_GetVideoUpscalerTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetVideoUpscalerLogs(ctx context.Context, in *QueryGetVideoUpscalerLogsRequest, opts ...grpc.CallOption) (*QueryGetVideoUpscalerLogsResponse, error) {
	out := new(QueryGetVideoUpscalerLogsResponse)
	err := c.cc.Invoke(ctx, Query_GetVideoUpscalerLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetWorker(ctx context.Context, in *QueryGetWorkerRequest, opts ...grpc.CallOption) (*QueryGetWorkerResponse, error) {
	out := new(QueryGetWorkerResponse)
	err := c.cc.Invoke(ctx, Query_GetWorker_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetPendingVideoUpscalerTasks(ctx context.Context, in *QueryGetPendingVideoUpscalerTaskRequest, opts ...grpc.CallOption) (*QueryGetPendingVideoUpscalerTaskResponse, error) {
	out := new(QueryGetPendingVideoUpscalerTaskResponse)
	err := c.cc.Invoke(ctx, Query_GetPendingVideoUpscalerTasks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// GetVideoUpscalerTask returns the task based on the taskId
	GetVideoUpscalerTask(context.Context, *QueryGetVideoUpscalerTaskRequest) (*QueryGetVideoUpscalerTaskResponse, error)
	GetVideoUpscalerLogs(context.Context, *QueryGetVideoUpscalerLogsRequest) (*QueryGetVideoUpscalerLogsResponse, error)
	GetWorker(context.Context, *QueryGetWorkerRequest) (*QueryGetWorkerResponse, error)
	GetPendingVideoUpscalerTasks(context.Context, *QueryGetPendingVideoUpscalerTaskRequest) (*QueryGetPendingVideoUpscalerTaskResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) GetVideoUpscalerTask(context.Context, *QueryGetVideoUpscalerTaskRequest) (*QueryGetVideoUpscalerTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoUpscalerTask not implemented")
}
func (UnimplementedQueryServer) GetVideoUpscalerLogs(context.Context, *QueryGetVideoUpscalerLogsRequest) (*QueryGetVideoUpscalerLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoUpscalerLogs not implemented")
}
func (UnimplementedQueryServer) GetWorker(context.Context, *QueryGetWorkerRequest) (*QueryGetWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorker not implemented")
}
func (UnimplementedQueryServer) GetPendingVideoUpscalerTasks(context.Context, *QueryGetPendingVideoUpscalerTaskRequest) (*QueryGetPendingVideoUpscalerTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPendingVideoUpscalerTasks not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_GetVideoUpscalerTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetVideoUpscalerTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetVideoUpscalerTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetVideoUpscalerTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetVideoUpscalerTask(ctx, req.(*QueryGetVideoUpscalerTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetVideoUpscalerLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetVideoUpscalerLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetVideoUpscalerLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetVideoUpscalerLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetVideoUpscalerLogs(ctx, req.(*QueryGetVideoUpscalerLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetWorker(ctx, req.(*QueryGetWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetPendingVideoUpscalerTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPendingVideoUpscalerTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetPendingVideoUpscalerTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetPendingVideoUpscalerTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetPendingVideoUpscalerTasks(ctx, req.(*QueryGetPendingVideoUpscalerTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "janction.videoUpscaler.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVideoUpscalerTask",
			Handler:    _Query_GetVideoUpscalerTask_Handler,
		},
		{
			MethodName: "GetVideoUpscalerLogs",
			Handler:    _Query_GetVideoUpscalerLogs_Handler,
		},
		{
			MethodName: "GetWorker",
			Handler:    _Query_GetWorker_Handler,
		},
		{
			MethodName: "GetPendingVideoUpscalerTasks",
			Handler:    _Query_GetPendingVideoUpscalerTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "janction/videoUpscaler/v1/query.proto",
}
